(define (problem sala)
    (:domain salas)
    (:objects Sala0 Sala1 Sala2 Sala2 Sala3  Sala4  Sala5  Sala6)
    (:init  (Em Sala0) 
            (Sala Sala0) (Sala Sala1) (Sala Sala2) (Sala Sala3) (Sala Sala4) (Sala Sala5) (Sala Sala6) 
            (PortaAberta Sala0) (PortaAberta Sala1) (PortaAberta Sala2) (PortaAberta Sala3) (PortaAberta Sala4) (PortaAberta Sala5) (PortaAberta Sala6)
            (JanelasAbertas Sala1) (JanelasAbertas Sala2) (JanelasAbertas Sala3) (JanelasAbertas Sala4) (JanelasAbertas Sala5) (JanelasAbertas Sala6)
            (Conexao Sala0 Sala1) (Conexao Sala0 Sala6)
            (Conexao Sala1 Sala0) (Conexao Sala6 Sala0)
            (Conexao Sala1 Sala2) (Conexao Sala2 Sala3)
            (Conexao Sala2 Sala1) (Conexao Sala3 Sala2)
            (Conexao Sala6 Sala5) (Conexao Sala5 Sala4)
            (Conexao Sala5 Sala6) (Conexao Sala4 Sala5)
            (LuzesAcesas Sala1) (LuzesAcesas Sala2) (LuzesAcesas Sala3) (LuzesAcesas Sala4) (LuzesAcesas Sala5) (LuzesAcesas Sala6) )
    (:goal  (and (LuzesApagadas Sala1) (LuzesApagadas Sala2) (LuzesApagadas Sala3) (LuzesApagadas Sala4) (LuzesApagadas Sala5) (LuzesApagadas Sala6)
                 (JanelasFechadas Sala1) (JanelasFechadas Sala2) (JanelasFechadas Sala3) (JanelasFechadas Sala4) (JanelasFechadas Sala5) (JanelasFechadas Sala6)
                 (PortaFechada Sala1) (PortaFechada Sala2) (PortaFechada Sala3) (PortaFechada Sala4) (PortaFechada Sala5) (PortaFechada Sala6)
                 (Em Sala0)
            )
        )
)
